### ISSUE TITLE
File names are pruned in output file

### ISSUE THREAD

**Issue by karlosos** [kkoripl/NaryaKeyPointsDatasetCreator#1]
I was trying to create a dataset using NaryaKeyPointsDatasetCreater served from the main branch (https://github.com/kkoripl/NaryaKeyPointsDatasetCreator/commit/39cad095184842645d8056c8370934e95414cbb4). 

![image](https://user-images.githubusercontent.com/3882385/108086171-60f43100-7076-11eb-8ce7-5c0f0d52618b.png)

However, the zip output file contains only a single pair of image and XML:

![image](https://user-images.githubusercontent.com/3882385/108086243-749f9780-7076-11eb-9596-6fe69186ca3c.png)

As you can see filename was pruned to `III liga_ Bałtyk Gdynia - KP Starogard Gdański (03.jpg`.

I have also created a heap snapshot in Google Chrome as I hope I will be able to save this hour of manual work somehow.

**Comment by karlosos** [comment]
Hmmm, ok I see that creating a heap snapshot won't help. Having short names fixes this problem.

**Comment by kkoripl** [comment]
The problem with names is, I was naive enough to look for the images extensions by the dot inside of it's name. It was made, cause Narya at first have only served .jpg's formats. I'd revert last commit and everything should be fine. 
Right now remove all the dots from inside the names and it should work.

**Comment by kkoripl** [comment]
Ok, it should be solved by this commits:

- [Revert of creating only .jpg files in dataset](https://github.com/kkoripl/NaryaKeyPointsDatasetCreator/commit/b73aba2244dc7d14a25c7928bd9c10a1174bde62)
- [Change of way to get extension from file name]( https://github.com/kkoripl/NaryaKeyPointsDatasetCreator/commit/dfcc12f480a9bc86b2c8845679df35be1a0ed483)

Feel free to reopen, if something will be still not right.
